version: '3.8'
services:
  api:
    build:
      target: dev
    volumes:
      - ./:/src
    container_name: route-finder
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*